project:
  type: website
  resources:
    - "three-toy/"
    - projects/*.json
  output-dir: docs

website:
  title: "Stepan Paul"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: teaching.qmd
        text: Teaching
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - yeti
    css: styles.css
    toc: false


